name: greenblack
channels:
  - conda-forge
dependencies:
  - ipykernel=5.1.0
  - matplotlib=3.0.2
  - openpyxl=2.5.14
  - pandas=0.24.0
  - plotnine=0.5.1
  - psycopg2=2.7.7
  - python=3.7.1
  - requests=2.21.0
  - seaborn=0.9.0
  - tqdm=4.29.1
  - xlrd=1.2.0
  - xz=5.2.4
  - pip:
    - scikit-misc==0.1.1
